import React, { useMemo, useState } from 'react';
import { Check, Plus, X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { dateLabel, downloadCSV } from '../utils/helpers';
import Modal from '../components/Modal';
import { Avatar, ExportButton, MobileDataList, PageHeader, SearchField, Status } from '../components/UI';

export default function Leave(){
  const {leaves,setLeaves,employees}=useApp(); const [q,setQ]=useState(''); const [filter,setFilter]=useState('All'); const [open,setOpen]=useState(false); const [form,setForm]=useState({employeeId:employees[0]?.id||'',type:'Casual Leave',from:'2026-09-15',to:'2026-09-15',reason:''});
  const rows=useMemo(()=>leaves.filter(l=>l.employee.toLowerCase().includes(q.toLowerCase())&&(filter==='All'||l.status===filter)),[leaves,q,filter]);
  const update=(id,status)=>setLeaves(list=>list.map(l=>l.id===id?{...l,status}:l));
  const submit=()=>{const emp=employees.find(e=>e.id===form.employeeId); if(!emp)return; const d1=new Date(form.from),d2=new Date(form.to); const days=Math.max(1,Math.round((d2-d1)/86400000)+1); setLeaves(x=>[{id:`LV-${Date.now()}`,employeeId:emp.id,employee:emp.name,days,status:'Pending',...form},...x]); setOpen(false);};
  return <>
    <PageHeader title="Leave Management" subtitle="Review employee leave requests and track approval status." actions={<><ExportButton onClick={()=>downloadCSV('leave-requests.csv',rows)}/><button className="button primary" onClick={()=>setOpen(true)}><Plus size={16}/>New Request</button></>}/>
    <div className="leave-tabs">{['All','Pending','Approved','Rejected'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}<span>{x==='All'?leaves.length:leaves.filter(l=>l.status===x).length}</span></button>)}</div>
    <section className="panel"><div className="toolbar"><SearchField value={q} onChange={setQ} placeholder="Search employee…"/></div><div className="desktop-table"><table><thead><tr><th>Employee</th><th>Leave Type</th><th>Dates</th><th>Days</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(l=><tr key={l.id}><td><div className="employee-cell"><Avatar name={l.employee}/><strong>{l.employee}</strong></div></td><td>{l.type}</td><td>{dateLabel(l.from)} – {dateLabel(l.to)}</td><td>{l.days}</td><td className="reason-cell">{l.reason}</td><td><Status value={l.status}/></td><td>{l.status==='Pending'?<div className="row-actions"><button className="icon-button success" onClick={()=>update(l.id,'Approved')} title="Approve"><Check size={16}/></button><button className="icon-button danger" onClick={()=>update(l.id,'Rejected')} title="Reject"><X size={16}/></button></div>:<span className="muted">Reviewed</span>}</td></tr>)}</tbody></table></div>
    <MobileDataList rows={rows} render={l=><div className="mobile-record" key={l.id}><div className="record-head"><div><strong>{l.employee}</strong><span>{l.type}</span></div><Status value={l.status}/></div><div className="record-grid"><span><small>From</small>{dateLabel(l.from)}</span><span><small>To</small>{dateLabel(l.to)}</span><span><small>Days</small>{l.days}</span><span><small>Reason</small>{l.reason}</span></div>{l.status==='Pending'&&<div className="record-actions"><button className="button success-button" onClick={()=>update(l.id,'Approved')}>Approve</button><button className="button danger-button" onClick={()=>update(l.id,'Rejected')}>Reject</button></div>}</div>}/></section>
    <Modal open={open} onClose={()=>setOpen(false)} title="Create Leave Request" subtitle="Add a leave request on behalf of an employee." footer={<><button className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button primary" onClick={submit}>Create Request</button></>}><div className="form-grid"><label className="field full"><span>Employee</span><select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.id}</option>)}</select></label><label className="field"><span>Leave type</span><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Casual Leave</option><option>Annual Leave</option><option>Sick Leave</option><option>Unpaid Leave</option></select></label><label className="field"><span>From</span><input type="date" value={form.from} onChange={e=>setForm({...form,from:e.target.value})}/></label><label className="field"><span>To</span><input type="date" value={form.to} onChange={e=>setForm({...form,to:e.target.value})}/></label><label className="field full"><span>Reason</span><textarea rows="3" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div></Modal>
  </>;
}
