import React, { useMemo, useState } from 'react';
import { Award, Star, Target, TrendingUp } from 'lucide-react';
import { useApp } from '../context/AppContext';
import Modal from '../components/Modal';
import { Avatar, MobileDataList, PageHeader, SearchField, StatCard, Status } from '../components/UI';

export default function Performance(){
  const {reviews,setReviews}=useApp(); const [q,setQ]=useState(''); const [selected,setSelected]=useState(null); const rows=useMemo(()=>reviews.filter(r=>`${r.employee} ${r.department}`.toLowerCase().includes(q.toLowerCase())),[reviews,q]); const avg=Math.round(reviews.reduce((s,r)=>s+r.score,0)/reviews.length);
  const save=()=>{setReviews(list=>list.map(r=>r.id===selected.id?selected:r));setSelected(null)};
  return <>
    <PageHeader title="Performance" subtitle="Track performance reviews, goals and employee ratings."/>
    <div className="stats-grid four"><StatCard icon={TrendingUp} label="Average Score" value={`${avg}%`} tone="green"/><StatCard icon={Award} label="Excellent" value={reviews.filter(r=>r.score>=90).length} tone="purple"/><StatCard icon={Target} label="Goals Completed" value={reviews.reduce((s,r)=>s+r.completed,0)} tone="blue"/><StatCard icon={Star} label="Needs Review" value={reviews.filter(r=>r.score<80).length} tone="orange"/></div>
    <section className="panel"><div className="toolbar"><SearchField value={q} onChange={setQ} placeholder="Search employee or department…"/></div><div className="desktop-table"><table><thead><tr><th>Employee</th><th>Department</th><th>Period</th><th>Score</th><th>Goals</th><th>Rating</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><div className="employee-cell"><Avatar name={r.employee}/><strong>{r.employee}</strong></div></td><td>{r.department}</td><td>{r.period}</td><td><div className="score-bar"><span style={{width:`${r.score}%`}}/><strong>{r.score}%</strong></div></td><td>{r.completed}/{r.goals}</td><td><Status value={r.rating}/></td><td><button className="text-link" onClick={()=>setSelected({...r})}>Review</button></td></tr>)}</tbody></table></div>
    <MobileDataList rows={rows} render={r=><div className="mobile-record" key={r.id}><div className="record-head"><div><strong>{r.employee}</strong><span>{r.department}</span></div><Status value={r.rating}/></div><div className="performance-score"><strong>{r.score}%</strong><span><i style={{width:`${r.score}%`}}/></span></div><div className="record-grid"><span><small>Period</small>{r.period}</span><span><small>Goals</small>{r.completed}/{r.goals}</span></div><button className="button secondary full-button" onClick={()=>setSelected({...r})}>Open Review</button></div>}/></section>
    <Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?`Review · ${selected.employee}`:'Review'} footer={<><button className="button secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="button primary" onClick={save}>Save Review</button></>}>{selected&&<div className="form-grid"><label className="field"><span>Score</span><input type="number" min="0" max="100" value={selected.score} onChange={e=>setSelected({...selected,score:Number(e.target.value),rating:Number(e.target.value)>=90?'Excellent':Number(e.target.value)>=80?'Good':'Needs Improvement'})}/></label><label className="field"><span>Completed goals</span><input type="number" min="0" max={selected.goals} value={selected.completed} onChange={e=>setSelected({...selected,completed:Number(e.target.value)})}/></label><label className="field full"><span>Manager note</span><textarea rows="5" value={selected.note} onChange={e=>setSelected({...selected,note:e.target.value})}/></label></div>}</Modal>
  </>;
}
